Author: Wandelbots GmbH
Copyright: Copyright (c) Wandelbots GmbH.
DefaultLocale: en-US
InstallModes:
- silent
- silentWithProgress
InstallerLocale: en-US
InstallerType: zip
Installers:
- Architecture: x64
  InstallerSha256: 47efbd5ccaf95e188d97ffa393aa913404710df2e57a0ea52c7caa3cb0c26f25
  InstallerUrl: https://github.com/wandelbotsgmbh/nova-cli/releases/download/0.0.242/novacli_win64-0.0.242.zip
  NestedInstallerFiles:
  - PortableCommandAlias: nova
    RelativeFilePath: nova.exe
  NestedInstallerType: portable
License: Apache 2.0
ManifestType: merged
ManifestVersion: 1.4.0
Moniker: novacli
PackageIdentifier: WandelbotsGmbH.NovaCLI
PackageLocale: en-US
PackageName: NovaCLI
PackageUrl: https://github.com/wandelbotsgmbh/nova-cli
PackageVersion: 0.0.242
Publisher: Wandelbots GmbH
PublisherSupportUrl: https://github.com/wandelbotsgmbh/nova-cli
PublisherUrl: https://www.wandelbots.com/
Scope: user
ShortDescription: Command line tool for interacting with the Wandelbots Nova.
Tags:
- wandelbots
- nova
UpgradeBehavior: uninstallPrevious
