InstallModes:
- silent
- silentWithProgress
InstallerLocale: en-US
InstallerType: zip
Installers:
- Architecture: x64
  InstallerSha256: 26ae53130752b7922a9d5f48c9bf3b21fdff2dd03bd006fe4878f97a9b9ecc53
  InstallerUrl: https://github.com/wandelbotsgmbh/nova-cli/releases/download/0.0.175/novacli_win64-0.0.175.zip
  NestedInstallerFiles:
  - PortableCommandAlias: nova
    RelativeFilePath: nova.exe
  NestedInstallerType: portable
ManifestType: installer
ManifestVersion: 1.4.0
PackageIdentifier: WandelbotsGmbH.NovaCLI
PackageVersion: 0.0.175
Scope: user
UpgradeBehavior: uninstallPrevious
