InstallModes:
- silent
- silentWithProgress
InstallerLocale: en-US
InstallerType: zip
Installers:
- Architecture: x64
  InstallerSha256: 0195dba763a0e6a30f97118d073acf3334e3e2b0c514b71306e8557543888f00
  InstallerUrl: https://github.com/wandelbotsgmbh/nova-cli/releases/download/0.0.198/novacli_win64-0.0.198.zip
  NestedInstallerFiles:
  - PortableCommandAlias: nova
    RelativeFilePath: nova.exe
  NestedInstallerType: portable
ManifestType: installer
ManifestVersion: 1.4.0
PackageIdentifier: WandelbotsGmbH.NovaCLI
PackageVersion: 0.0.198
Scope: user
UpgradeBehavior: uninstallPrevious
