InstallModes:
- silent
- silentWithProgress
InstallerLocale: en-US
InstallerType: zip
Installers:
- Architecture: x64
  InstallerSha256: 1a64f8d1901f1bd295d4cff3a062de45aedeb031b07de9b3d44419de7bfea89a
  InstallerUrl: https://github.com/wandelbotsgmbh/nova-cli/releases/download/0.0.199/novacli_win64-0.0.199.zip
  NestedInstallerFiles:
  - PortableCommandAlias: nova
    RelativeFilePath: nova.exe
  NestedInstallerType: portable
ManifestType: installer
ManifestVersion: 1.4.0
PackageIdentifier: WandelbotsGmbH.NovaCLI
PackageVersion: 0.0.199
Scope: user
UpgradeBehavior: uninstallPrevious
