Author: Wandelbots GmbH
Copyright: Copyright (c) Wandelbots GmbH.
DefaultLocale: en-US
InstallModes:
- silent
- silentWithProgress
InstallerLocale: en-US
InstallerType: zip
Installers:
- Architecture: x64
  InstallerSha256: 52d105d28e6ba6aab5aa5ef7a91a234f9a7f3c5981d5d6f7d4c5ce247da52644
  InstallerUrl: https://github.com/wandelbotsgmbh/nova-cli/releases/download/0.0.239/novacli_win64-0.0.239.zip
  NestedInstallerFiles:
  - PortableCommandAlias: nova
    RelativeFilePath: nova.exe
  NestedInstallerType: portable
License: Apache 2.0
ManifestType: merged
ManifestVersion: 1.4.0
Moniker: novacli
PackageIdentifier: WandelbotsGmbH.NovaCLI
PackageLocale: en-US
PackageName: NovaCLI
PackageUrl: https://github.com/wandelbotsgmbh/nova-cli
PackageVersion: 0.0.239
Publisher: Wandelbots GmbH
PublisherSupportUrl: https://github.com/wandelbotsgmbh/nova-cli
PublisherUrl: https://www.wandelbots.com/
Scope: user
ShortDescription: Command line tool for interacting with the Wandelbots Nova.
Tags:
- wandelbots
- nova
UpgradeBehavior: uninstallPrevious
