InstallModes:
- silent
- silentWithProgress
InstallerLocale: en-US
InstallerType: zip
Installers:
- Architecture: x64
  InstallerSha256: e1d288c4d693b32e2026b0a09aa2fe83879439e22021688dc0df51711ea767d0
  InstallerUrl: https://github.com/wandelbotsgmbh/nova-cli/releases/download/0.0.171/novacli_win64-0.0.171.zip
  NestedInstallerFiles:
  - PortableCommandAlias: nova
    RelativeFilePath: nova.exe
  NestedInstallerType: portable
ManifestType: installer
ManifestVersion: 1.4.0
PackageIdentifier: WandelbotsGmbH.NovaCLI
PackageVersion: 0.0.171
Scope: user
UpgradeBehavior: uninstallPrevious
