InstallModes:
- silent
- silentWithProgress
InstallerLocale: en-US
InstallerType: zip
Installers:
- Architecture: x64
  InstallerSha256: 1f4bd6994e72cc18b770216505a8fb3a2b686874d0c897ada15d4463b1b63926
  InstallerUrl: https://github.com/wandelbotsgmbh/nova-cli/releases/download/0.0.200/novacli_win64-0.0.200.zip
  NestedInstallerFiles:
  - PortableCommandAlias: nova
    RelativeFilePath: nova.exe
  NestedInstallerType: portable
ManifestType: installer
ManifestVersion: 1.4.0
PackageIdentifier: WandelbotsGmbH.NovaCLI
PackageVersion: 0.0.200
Scope: user
UpgradeBehavior: uninstallPrevious
