InstallModes:
- silent
- silentWithProgress
InstallerLocale: en-US
InstallerType: zip
Installers:
- Architecture: x64
  InstallerSha256: bla
  InstallerUrl: https://github.com/wandelbotsgmbh/nova-cli/releases/download/6.6.7/novacli_win64-6.6.7.zip
  NestedInstallerFiles:
  - PortableCommandAlias: nova
    RelativeFilePath: nova.exe
  NestedInstallerType: portable
ManifestType: installer
ManifestVersion: 1.4.0
PackageIdentifier: WandelbotsGmbH.NovaCLI
PackageVersion: 6.6.7
Scope: user
UpgradeBehavior: uninstallPrevious
