InstallModes:
- silent
- silentWithProgress
InstallerLocale: en-US
InstallerType: zip
Installers:
- Architecture: x64
  InstallerSha256: 96652d362ed4eb012b40147185564cc7fb4e332f4c183d9ea8c177b3a4933ebd
  InstallerUrl: https://github.com/wandelbotsgmbh/nova-cli/releases/download/0.0.223/novacli_win64-0.0.223.zip
  NestedInstallerFiles:
  - PortableCommandAlias: nova
    RelativeFilePath: nova.exe
  NestedInstallerType: portable
ManifestType: installer
ManifestVersion: 1.4.0
PackageIdentifier: WandelbotsGmbH.NovaCLI
PackageVersion: 0.0.223
Scope: user
UpgradeBehavior: uninstallPrevious
