InstallModes:
- silent
- silentWithProgress
InstallerLocale: en-US
InstallerType: zip
Installers:
- Architecture: x64
  InstallerSha256: 77a5741c801d2800b205317fdf67a5180403dcc2807b3844499bbb2fecbf7e3e
  InstallerUrl: https://github.com/wandelbotsgmbh/nova-cli/releases/download/0.0.202/novacli_win64-0.0.202.zip
  NestedInstallerFiles:
  - PortableCommandAlias: nova
    RelativeFilePath: nova.exe
  NestedInstallerType: portable
ManifestType: installer
ManifestVersion: 1.4.0
PackageIdentifier: WandelbotsGmbH.NovaCLI
PackageVersion: 0.0.202
Scope: user
UpgradeBehavior: uninstallPrevious
