Author: Wandelbots GmbH
Copyright: Copyright (c) Wandelbots GmbH.
DefaultLocale: en-US
InstallModes:
- silent
- silentWithProgress
InstallerLocale: en-US
InstallerType: zip
Installers:
- Architecture: x64
  InstallerSha256: e5df9377db3931c58908916665a77c791fad51ba455d9d4a043545960e9217bd
  InstallerUrl: https://github.com/wandelbotsgmbh/nova-cli/releases/download/0.0.236/novacli_win64-0.0.236.zip
  NestedInstallerFiles:
  - PortableCommandAlias: nova
    RelativeFilePath: nova.exe
  NestedInstallerType: portable
License: Apache 2.0
ManifestType: merged
ManifestVersion: 1.4.0
Moniker: novacli
PackageIdentifier: WandelbotsGmbH.NovaCLI
PackageLocale: en-US
PackageName: NovaCLI
PackageUrl: https://github.com/wandelbotsgmbh/nova-cli
PackageVersion: 0.0.236
Publisher: Wandelbots GmbH
PublisherSupportUrl: https://github.com/wandelbotsgmbh/nova-cli
PublisherUrl: https://www.wandelbots.com/
Scope: user
ShortDescription: Command line tool for interacting with the Wandelbots Nova.
Tags:
- wandelbots
- nova
UpgradeBehavior: uninstallPrevious
