InstallModes:
- silent
- silentWithProgress
InstallerLocale: en-US
InstallerType: zip
Installers:
- Architecture: x64
  InstallerSha256: 9dfb7fa9a08315ac5625019d1599732b4f8f475e8244ef51c18e0dbdd15eaaba
  InstallerUrl: https://github.com/wandelbotsgmbh/nova-cli/releases/download/0.0.188/novacli_win64-0.0.188.zip
  NestedInstallerFiles:
  - PortableCommandAlias: nova
    RelativeFilePath: nova.exe
  NestedInstallerType: portable
ManifestType: installer
ManifestVersion: 1.4.0
PackageIdentifier: WandelbotsGmbH.NovaCLI
PackageVersion: 0.0.188
Scope: user
UpgradeBehavior: uninstallPrevious
