InstallModes:
- silent
- silentWithProgress
InstallerLocale: en-US
InstallerType: zip
Installers:
- Architecture: x64
  InstallerSha256: e216f381543061b920a78a0d5ecce1f53afaeb76effc3fe192f0ed216d6adca7
  InstallerUrl: https://github.com/wandelbotsgmbh/nova-cli/releases/download/0.0.232/novacli_win64-0.0.232.zip
  NestedInstallerFiles:
  - PortableCommandAlias: nova
    RelativeFilePath: nova.exe
  NestedInstallerType: portable
ManifestType: installer
ManifestVersion: 1.4.0
PackageIdentifier: WandelbotsGmbH.NovaCLI
PackageVersion: 0.0.232
Scope: user
UpgradeBehavior: uninstallPrevious
