InstallModes:
- silent
- silentWithProgress
InstallerLocale: en-US
InstallerType: zip
Installers:
- Architecture: x64
  InstallerSha256: 4c61ff81d665afbf8fbb2c0c46a83891bab86b96768fff3d2a95d8b30b9fc8cb
  InstallerUrl: https://github.com/wandelbotsgmbh/nova-cli/releases/download/0.0.181/novacli_win64-0.0.181.zip
  NestedInstallerFiles:
  - PortableCommandAlias: nova
    RelativeFilePath: nova.exe
  NestedInstallerType: portable
ManifestType: installer
ManifestVersion: 1.4.0
PackageIdentifier: WandelbotsGmbH.NovaCLI
PackageVersion: 0.0.181
Scope: user
UpgradeBehavior: uninstallPrevious
