InstallModes:
- silent
- silentWithProgress
InstallerLocale: en-US
InstallerType: zip
Installers:
- Architecture: x64
  InstallerSha256: d5fef2192fbf73ebb7fe8f0721e26d45f0c8587617fa8c08dff9d84a68ca4202
  InstallerUrl: https://github.com/wandelbotsgmbh/nova-cli/releases/download/0.0.187/novacli_win64-0.0.187.zip
  NestedInstallerFiles:
  - PortableCommandAlias: nova
    RelativeFilePath: nova.exe
  NestedInstallerType: portable
ManifestType: installer
ManifestVersion: 1.4.0
PackageIdentifier: WandelbotsGmbH.NovaCLI
PackageVersion: 0.0.187
Scope: user
UpgradeBehavior: uninstallPrevious
