InstallModes:
- silent
- silentWithProgress
InstallerLocale: en-US
InstallerType: zip
Installers:
- Architecture: x64
  InstallerSha256: e4e8f8a99913ab0a9f8ecfa7512c281e07f02a9aac90e98d2e46d993ca92a4d6
  InstallerUrl: https://github.com/wandelbotsgmbh/nova-cli/releases/download/0.0.183/novacli_win64-0.0.183.zip
  NestedInstallerFiles:
  - PortableCommandAlias: nova
    RelativeFilePath: nova.exe
  NestedInstallerType: portable
ManifestType: installer
ManifestVersion: 1.4.0
PackageIdentifier: WandelbotsGmbH.NovaCLI
PackageVersion: 0.0.183
Scope: user
UpgradeBehavior: uninstallPrevious
