InstallModes:
- silent
- silentWithProgress
InstallerLocale: en-US
InstallerType: zip
Installers:
- Architecture: x64
  InstallerSha256: 46ab2e8fe5fb4fe782d721e2b0330f83189a0b0ea90465488fb8e53fa77ae4f1
  InstallerUrl: https://github.com/wandelbotsgmbh/nova-cli/releases/download/0.0.212/novacli_win64-0.0.212.zip
  NestedInstallerFiles:
  - PortableCommandAlias: nova
    RelativeFilePath: nova.exe
  NestedInstallerType: portable
ManifestType: installer
ManifestVersion: 1.4.0
PackageIdentifier: WandelbotsGmbH.NovaCLI
PackageVersion: 0.0.212
Scope: user
UpgradeBehavior: uninstallPrevious
