InstallModes:
- silent
- silentWithProgress
InstallerLocale: en-US
InstallerType: zip
Installers:
- Architecture: x64
  InstallerSha256: f6dc895a26fd289c4e65f1aec037389845e08e0cad658d72b40aca7574d32577
  InstallerUrl: https://github.com/wandelbotsgmbh/nova-cli/releases/download/0.0.208/novacli_win64-0.0.208.zip
  NestedInstallerFiles:
  - PortableCommandAlias: nova
    RelativeFilePath: nova.exe
  NestedInstallerType: portable
ManifestType: installer
ManifestVersion: 1.4.0
PackageIdentifier: WandelbotsGmbH.NovaCLI
PackageVersion: 0.0.208
Scope: user
UpgradeBehavior: uninstallPrevious
