InstallModes:
- silent
- silentWithProgress
InstallerLocale: en-US
InstallerType: zip
Installers:
- Architecture: x64
  InstallerSha256: be933ee767cc496c866f847dd39d88153dee7221af8e91845afc331e86f81b83
  InstallerUrl: https://github.com/wandelbotsgmbh/nova-cli/releases/download/0.0.211/novacli_win64-0.0.211.zip
  NestedInstallerFiles:
  - PortableCommandAlias: nova
    RelativeFilePath: nova.exe
  NestedInstallerType: portable
ManifestType: installer
ManifestVersion: 1.4.0
PackageIdentifier: WandelbotsGmbH.NovaCLI
PackageVersion: 0.0.211
Scope: user
UpgradeBehavior: uninstallPrevious
