Author: Wandelbots GmbH
Copyright: Copyright (c) Wandelbots GmbH.
DefaultLocale: en-US
InstallModes:
- silent
- silentWithProgress
InstallerLocale: en-US
InstallerType: zip
Installers:
- Architecture: x64
  InstallerSha256: dbb88a2b4fcf4cdf3b0ad31fe987a6dc3340cb3401d0fc49c359cbc927d4b5ac
  InstallerUrl: https://github.com/wandelbotsgmbh/nova-cli/releases/download/0.0.222/novacli_win64-0.0.222.zip
  NestedInstallerFiles:
  - PortableCommandAlias: nova
    RelativeFilePath: nova.exe
  NestedInstallerType: portable
License: Apache 2.0
ManifestType: merged
ManifestVersion: 1.4.0
Moniker: novacli
PackageIdentifier: WandelbotsGmbH.NovaCLI
PackageLocale: en-US
PackageName: NovaCLI
PackageUrl: https://github.com/wandelbotsgmbh/nova-cli
PackageVersion: 0.0.222
Publisher: Wandelbots GmbH
PublisherSupportUrl: https://github.com/wandelbotsgmbh/nova-cli
PublisherUrl: https://www.wandelbots.com/
Scope: user
ShortDescription: Command line tool for interacting with the Wandelbots Nova.
Tags:
- wandelbots
- nova
UpgradeBehavior: uninstallPrevious
