InstallModes:
- silent
- silentWithProgress
InstallerLocale: en-US
InstallerType: zip
Installers:
- Architecture: x64
  InstallerSha256: 85e7b19b707764f33f64f785454b7fb63f8656e63dab1aa028af1dde49011a90
  InstallerUrl: https://github.com/wandelbotsgmbh/nova-cli/releases/download/0.0.190/novacli_win64-0.0.190.zip
  NestedInstallerFiles:
  - PortableCommandAlias: nova
    RelativeFilePath: nova.exe
  NestedInstallerType: portable
ManifestType: installer
ManifestVersion: 1.4.0
PackageIdentifier: WandelbotsGmbH.NovaCLI
PackageVersion: 0.0.190
Scope: user
UpgradeBehavior: uninstallPrevious
