InstallModes:
- silent
- silentWithProgress
InstallerLocale: en-US
InstallerType: zip
Installers:
- Architecture: x64
  InstallerSha256: 19084df796f5d1d8c788b45f35e3335542d9ae909a9df93d0a9fc46bcb8c7ea0
  InstallerUrl: https://github.com/wandelbotsgmbh/nova-cli/releases/download/0.0.184/novacli_win64-0.0.184.zip
  NestedInstallerFiles:
  - PortableCommandAlias: nova
    RelativeFilePath: nova.exe
  NestedInstallerType: portable
ManifestType: installer
ManifestVersion: 1.4.0
PackageIdentifier: WandelbotsGmbH.NovaCLI
PackageVersion: 0.0.184
Scope: user
UpgradeBehavior: uninstallPrevious
