InstallModes:
- silent
- silentWithProgress
InstallerLocale: en-US
InstallerType: zip
Installers:
- Architecture: x64
  InstallerSha256: e13b3a2a1634623397b30ba1e54f3304e87ce5c174d7dadd920f70328647d3ec
  InstallerUrl: https://github.com/wandelbotsgmbh/nova-cli/releases/download/0.0.225/novacli_win64-0.0.225.zip
  NestedInstallerFiles:
  - PortableCommandAlias: nova
    RelativeFilePath: nova.exe
  NestedInstallerType: portable
ManifestType: installer
ManifestVersion: 1.4.0
PackageIdentifier: WandelbotsGmbH.NovaCLI
PackageVersion: 0.0.225
Scope: user
UpgradeBehavior: uninstallPrevious
