---
name: Build Winget Source

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  lint-yaml:
    name: Build Winget Source
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      
      - name: Install Python
        run: |
          cd scripts
          uv python install

      - name: Build Source Index And Manifests
        run: |
          cd scripts
          uv run 02-create-catalog.py

      - name: Deploy To gh-pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          folder: .