InstallModes:
- silent
- silentWithProgress
InstallerLocale: en-US
InstallerType: zip
Installers:
- Architecture: x64
  InstallerSha256: e81549bbab49093367f71c43049bb6426e3cea6eda58c4719b0d27deff33637a
  InstallerUrl: https://github.com/wandelbotsgmbh/nova-cli/releases/download/0.0.168/novacli_win64-0.0.168.zip
  NestedInstallerFiles:
  - PortableCommandAlias: nova
    RelativeFilePath: nova.exe
  NestedInstallerType: portable
ManifestType: installer
ManifestVersion: 1.4.0
PackageIdentifier: WandelbotsGmbH.NovaCLI
PackageVersion: 0.0.168
Scope: user
UpgradeBehavior: uninstallPrevious
